#!/usr/bin/bash

#!/bin/bash

files=(
    "_atoi.c"
    "builtin.c"
    "errors.c"
    "getinfo.c"
    "lists1.c"
    "memory.c"
    "realloc.c"
    "string1.c"
    "vars.c"
    "AUTHORS"
    "environ.c"
    "exits.c"
    "getLine.c"
    "lists.c"
    "parser.c"
    "shell.h"
    "string.c"
    "builtin1.c"
    "errors1.c"
    "getenv.c"
    "history.c"
    "main.c"
    "README.md"
    "shell_loop.c"
    "tokenizer.c"
)

for file in "${files[@]}"; do
    case $file in
        "_atoi.c") mv "$file" "string_to_integer.c" ;;
        "builtin.c") mv "$file" "builtin_commands.c" ;;
        "errors.c") mv "$file" "error_handling.c" ;;
        "getinfo.c") mv "$file" "get_information.c" ;;
        "lists1.c") mv "$file" "linked_lists_helper.c" ;;
        "memory.c") mv "$file" "memory_management.c" ;;
        "realloc.c") mv "$file" "reallocate_memory.c" ;;
        "string1.c") mv "$file" "string_helper.c" ;;
        "vars.c") mv "$file" "variables.c" ;;
        "getLine.c") mv "$file" "get_line.c" ;;
        "lists.c") mv "$file" "linked_lists.c" ;;
        "parser.c") mv "$file" "command_parser.c" ;;
        "string.c") mv "$file" "string_operations.c" ;;
        "builtin1.c") mv "$file" "builtin_commands_extended.c" ;;
        "errors1.c") mv "$file" "error_handling_extended.c" ;;
        "getenv.c") mv "$file" "get_environment_variable.c" ;;
        "history.c") mv "$file" "command_history.c" ;;
        "main.c") mv "$file" "main_program.c" ;;
        "shell_loop.c") mv "$file" "shell_execution_loop.c" ;;
        "tokenizer.c") mv "$file" "command_tokenizer.c" ;;
        *) echo "Skipping $file" ;;
    esac
done
